ORTHEALTH ; Provider health state
 ;
INIT ;
 DO SET("openai",$$HAS^ORTVAULT("openai"))
 DO SET("anthropic",$$HAS^ORTVAULT("anthropic"))
 QUIT
 ;
SET(PROVIDER,OK) ;
 SET ^ORTHO("HEALTH",PROVIDER,"OK")=OK
 SET ^ORTHO("HEALTH",PROVIDER,"TS")=$HOROLOG
 QUIT
 ;
CHECK(PROVIDER) ;
 NEW OK
 SET OK=$GET(^ORTHO("HEALTH",PROVIDER,"OK"))
 IF OK="" SET OK=$$HAS^ORTVAULT(PROVIDER) DO SET(PROVIDER,OK)
 QUIT OK

