ORTHOAI ; ORTHO AI gateway entry points
 ;
INIT ;
 DO INIT^ORTROUTE
 DO INIT^ORTHEALTH
 QUIT 1
 ;
REQ(ID,MODEL,PROMPT) ;
 NEW OK,PROVIDER,ERR
 IF ID="" QUIT 0
 LOCK +^ORTHO("REQ",ID):5 ELSE  DO  QUIT 0
 . SET ^ORTHO("REQ",ID,"STATE")="FAILED"
 . SET ^ORTHO("REQ",ID,"ERROR")="request lock timeout"
 SET ^ORTHO("REQ",ID,"STATE")="NEW"
 SET ^ORTHO("REQ",ID,"MODEL")=MODEL
 SET ^ORTHO("REQ",ID,"PROMPT")=PROMPT
 SET ^ORTHO("REQ",ID,"SEQ")=0
 DO EVENT^ORTSTREAM(ID,"state","NEW")
 SET ^ORTHO("REQ",ID,"STATE")="ROUTING"
 DO EVENT^ORTSTREAM(ID,"state","ROUTING")
 SET PROVIDER=$$RESOLVE^ORTROUTE(MODEL)
 IF PROVIDER="" DO FAIL(ID,"route failed") LOCK -^ORTHO("REQ",ID) QUIT 0
 SET ^ORTHO("REQ",ID,"PROVIDER")=PROVIDER
 SET OK=$$CHECK^ORTHEALTH(PROVIDER)
 IF 'OK DO FAIL(ID,"provider unhealthy or unconfigured") LOCK -^ORTHO("REQ",ID) QUIT 0
 SET ^ORTHO("REQ",ID,"STATE")="RUNNING"
 DO EVENT^ORTSTREAM(ID,"route",MODEL_" -> "_PROVIDER)
 DO EVENT^ORTSTREAM(ID,"state","RUNNING")
 SET ERR=$$CALL^ORTPROV(ID,PROVIDER,PROMPT)
 IF ERR DO FAIL(ID,$GET(^ORTHO("REQ",ID,"ERROR"),"provider failed")) LOCK -^ORTHO("REQ",ID) QUIT 0
 IF $$TERM(ID) LOCK -^ORTHO("REQ",ID) QUIT 0
 SET ^ORTHO("REQ",ID,"STATE")="DONE"
 DO EVENT^ORTSTREAM(ID,"state","DONE")
 DO RECORD^ORTUSAGE(ID)
 LOCK -^ORTHO("REQ",ID)
 QUIT 1
 ;
CANCEL(ID) ;
 LOCK +^ORTHO("REQ",ID):5 ELSE  QUIT 0
 IF $$TERM(ID) LOCK -^ORTHO("REQ",ID) QUIT 0
 SET ^ORTHO("REQ",ID,"STATE")="CANCELLED"
 DO EVENT^ORTSTREAM(ID,"state","CANCELLED")
 LOCK -^ORTHO("REQ",ID)
 QUIT 1
 ;
FAIL(ID,MSG) ;
 IF $$TERM(ID) QUIT
 SET ^ORTHO("REQ",ID,"STATE")="FAILED"
 SET ^ORTHO("REQ",ID,"ERROR")=MSG
 DO FAIL^ORTSTREAM(ID,MSG)
 QUIT
 ;
TERM(ID) ;
 NEW S SET S=$GET(^ORTHO("REQ",ID,"STATE"))
 QUIT (S="DONE")!(S="FAILED")!(S="CANCELLED")
 ;
STATE(ID) ;
 QUIT $GET(^ORTHO("REQ",ID,"STATE"))

