ORTSTREAM ; Streaming event state
 ;
EVENT(ID,TYPE,VALUE) ;
 NEW SEQ
 LOCK +^ORTHO("REQ",ID,"SEQ"):5 ELSE  QUIT 0
 SET SEQ=$GET(^ORTHO("REQ",ID,"SEQ"))+1
 SET ^ORTHO("REQ",ID,"SEQ")=SEQ
 SET ^ORTHO("EVENT",ID,SEQ,"TYPE")=TYPE
 SET ^ORTHO("EVENT",ID,SEQ,"VALUE")=VALUE
 SET ^ORTHO("EVENT",ID,SEQ,"TS")=$HOROLOG
 LOCK -^ORTHO("REQ",ID,"SEQ")
 DO SEND^ORTIPC(ID,SEQ)
 QUIT 1
 ;
TOKEN(ID,TEXT) ;
 QUIT $$EVENT(ID,"token",TEXT)
 ;
FAIL(ID,MSG) ;
 QUIT $$EVENT(ID,"failed",MSG)

