ORTUSAGE ; Usage accounting
 ;
RECORD(ID) ;
 NEW PROVIDER,ALIAS,IN,OUT,N
 SET PROVIDER=$GET(^ORTHO("REQ",ID,"PROVIDER"))
 SET ALIAS=$GET(^ORTHO("REQ",ID,"MODEL"))
 SET IN=$LENGTH($GET(^ORTHO("REQ",ID,"PROMPT")))\4+1
 SET OUT=$GET(^ORTHO("REQ",ID,"SEQ"))
 LOCK +^ORTHO("USAGE"):5 ELSE  QUIT 0
 SET N=$GET(^ORTHO("USAGE",0))+1
 SET ^ORTHO("USAGE",0)=N
 SET ^ORTHO("USAGE",N,"REQ")=ID
 SET ^ORTHO("USAGE",N,"PROVIDER")=PROVIDER
 SET ^ORTHO("USAGE",N,"ALIAS")=ALIAS
 SET ^ORTHO("USAGE",N,"IN")=IN
 SET ^ORTHO("USAGE",N,"OUT")=OUT
 SET ^ORTHO("USAGE",N,"TS")=$HOROLOG
 LOCK -^ORTHO("USAGE")
 QUIT 1

