ORTACCEPT ; Runtime acceptance probe
 DO INIT^ORTHOAI
 SET OK=$$REQ^ORTHOAI("REQ-RUNTIME","missing.alias","hello")
 WRITE "REQUEST ID: REQ-RUNTIME",!
 WRITE "ROUTE: missing.alias",!
 WRITE "PROVIDER: none",!
 WRITE "STREAM SEQUENCE: ",$GET(^ORTHO("REQ","REQ-RUNTIME","SEQ")),!
 WRITE "TERMINAL STATE: ",$$STATE^ORTHOAI("REQ-RUNTIME"),!
 HALT

